export interface InhouseQuestion {
  id: string;
  section: string;
  question: string;
  type: "single" | "multi" | "scale";
  options?: string[];
  scaleMin?: number;
  scaleMax?: number;
  scaleLabels?: { min: string; max: string };
  scaleGuide?: { range: string; label: string }[];
  maxSelections?: number;
}

export const inhouseQuestions: InhouseQuestion[] = [
  {
    id: "q1",
    section: "Role & Company Context",
    question: "What best describes your role in hiring?",
    type: "single",
    options: [
      "In-house recruiter / talent acquisition",
      "HR manager / HR director",
      "Hiring manager",
      "Business owner / founder",
      "Department leader / executive",
    ],
  },
  {
    id: "q2",
    section: "Role & Company Context",
    question: "How many employees does your organisation have?",
    type: "single",
    options: ["1–25", "26–100", "101–250", "251–1000", "1000+"],
  },
  {
    id: "q3",
    section: "Role & Company Context",
    question: "How many hires does your organisation typically make per year?",
    type: "single",
    options: ["1–10", "11–25", "26–50", "51–100", "100+"],
  },
  {
    id: "q4",
    section: "Role & Company Context",
    question: "What types of roles do you hire most often?",
    type: "single",
    options: [
      "Operational / front-line",
      "Professional / specialist",
      "Commercial / sales",
      "Leadership / management",
      "Mixed roles",
    ],
  },
  {
    id: "q5",
    section: "Requirement Capture & Role Definition",
    question: "How clearly are roles usually defined before recruitment begins?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Low clarity", max: "Gold standard" },
    scaleGuide: [
      { range: "1–3", label: "Role requirements are vague. Job descriptions are reused or written quickly with limited stakeholder alignment." },
      { range: "4–6", label: "Role requirements are reasonably clear but often rely mainly on skills and experience rather than defining success in the role." },
      { range: "7–8", label: "Role expectations, responsibilities and success measures are clearly discussed with stakeholders before recruitment begins." },
      { range: "9–10", label: "A structured benchmarking process defines role outcomes, behavioural traits, motivational drivers and success criteria before sourcing begins." },
    ],
  },
  {
    id: "q6",
    section: "Requirement Capture & Role Definition",
    question: "How often do key stakeholders fully agree on what \"good\" looks like before recruitment begins?",
    type: "single",
    options: ["Rarely", "Sometimes", "Often", "Almost always"],
  },
  {
    id: "q7",
    section: "Requirement Capture & Role Definition",
    question: "Which of the following best describes your current process for defining a role?",
    type: "multi",
    maxSelections: 2,
    options: [
      "We reuse old job descriptions",
      "Hiring manager defines the role alone",
      "HR / TA refines the brief",
      "Multiple stakeholders align requirements before recruitment begins",
      "We create a job specification that clearly defines critical and desirable criteria based mostly on skills and experience",
      "We define behavioural success factors and outcomes before recruiting",
    ],
  },
  {
    id: "q8",
    section: "Job Adverts & Employer Branding",
    question: "How effective are your current job adverts at attracting high-quality aligned candidates?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Administrative", max: "Gold standard" },
    scaleGuide: [
      { range: "1–3", label: "Job adverts are largely administrative and describe responsibilities rather than selling the opportunity." },
      { range: "4–6", label: "Adverts communicate the role reasonably well but may not strongly differentiate the opportunity." },
      { range: "7–8", label: "Adverts are written to attract and engage strong candidates." },
      { range: "9–10", label: "Adverts clearly communicate the opportunity, growth, culture and success expectations while targeting the right candidate profile." },
    ],
  },
  {
    id: "q9",
    section: "Job Adverts & Employer Branding",
    question: "How would you best describe your current job advert writing style?",
    type: "multi",
    maxSelections: 2,
    options: [
      "Detailed job specifications",
      "Role responsibilities and requirements focused",
      "Opportunity-focused adverts designed to attract candidates",
      "Culture and growth story focused adverts",
      "Highly tailored role marketing campaigns",
    ],
  },
  {
    id: "q10",
    section: "Job Adverts & Employer Branding",
    question: "How strongly do you feel your employer brand helps you stand out to candidates?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Little differentiation", max: "Gold standard" },
    scaleGuide: [
      { range: "1–3", label: "Little differentiation from other employers." },
      { range: "4–6", label: "Employer brand is communicated but inconsistently." },
      { range: "7–8", label: "Candidates have a reasonably clear understanding of company culture and opportunity." },
      { range: "9–10", label: "Employer brand consistently attracts candidates aligned to company values and ambitions." },
    ],
  },
  {
    id: "q11",
    section: "Sourcing & Talent Pipeline",
    question: "Which sourcing channels do you rely on most?",
    type: "multi",
    maxSelections: 3,
    options: [
      "Job boards",
      "LinkedIn",
      "Internal database",
      "Referrals",
      "Passive candidate outreach",
      "Recruitment agencies",
      "Multi-channel campaigns",
    ],
  },
  {
    id: "q12",
    section: "Sourcing & Talent Pipeline",
    question: "How confident are you that your sourcing strategy reaches the best possible candidates, not just the most available ones?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Mostly inbound", max: "Gold standard" },
    scaleGuide: [
      { range: "1–3", label: "Mostly reliant on inbound applicants." },
      { range: "4–6", label: "Mix of inbound applicants and limited outreach." },
      { range: "7–8", label: "Proactive sourcing across several channels." },
      { range: "9–10", label: "Structured attraction campaigns targeting both active and passive candidates." },
    ],
  },
  {
    id: "q13",
    section: "Assessment & Evaluation",
    question: "Which statement best reflects your sourcing model?",
    type: "single",
    options: [
      "Mostly inbound applicants",
      "Limited sourcing channels",
      "Combination of inbound and outreach",
      "Targeted multi-channel campaign sourcing",
    ],
  },
  {
    id: "q14",
    section: "Assessment & Evaluation",
    question: "Before assessing candidates, how often do you define behavioural success factors?",
    type: "single",
    options: ["Never", "Occasionally", "Often", "Always"],
  },
  {
    id: "q15",
    section: "Assessment & Evaluation",
    question: "How structured is your candidate assessment process beyond CV review and interviews?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Mostly CV & interviews", max: "Gold standard" },
    scaleGuide: [
      { range: "1–3", label: "Mostly CV review and interviews." },
      { range: "4–6", label: "Some structured evaluation tools." },
      { range: "7–8", label: "Structured evaluation and behavioural questions." },
      { range: "9–10", label: "Benchmark-aligned behavioural assessment, questionnaires and structured evaluation." },
    ],
  },
  {
    id: "q16",
    section: "Assessment & Evaluation",
    question: "Which of the following applies to the way you currently operate?",
    type: "multi",
    maxSelections: 3,
    options: [
      "Manual CV screening only",
      "Parsing or AI screening tools",
      "Structured interview scorecards",
      "Behavioural benchmarks & questionnaires",
      "Psychometric / assessment tools",
      "Behavioural or competency-based interview framework",
      "Visual candidate comparison / score reports",
      "Final Fit & Risk analysis",
    ],
  },
  {
    id: "q17",
    section: "Assessment & Evaluation",
    question: "How consistent is candidate evaluation across interviewers and stakeholders?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Varies widely", max: "Gold standard" },
    scaleGuide: [
      { range: "1–3", label: "Evaluations vary widely." },
      { range: "4–6", label: "Some structure but still subjective." },
      { range: "7–8", label: "Consistent evaluation criteria used." },
      { range: "9–10", label: "Structured evaluation aligned to benchmark and candidate assessment data." },
    ],
  },
  {
    id: "q18",
    section: "Interview Quality & Decision Making",
    question: "How structured are your interviews?",
    type: "single",
    options: [
      "Mostly conversational and instinctive",
      "Partly structured but inconsistent",
      "Mostly structured and consistent",
      "Fully structured and aligned to the benchmark and early assessment outputs",
    ],
  },
  {
    id: "q19",
    section: "Interview Quality & Decision Making",
    question: "How often do you validate interview impressions with structured evidence?",
    type: "single",
    options: ["Never", "Occasionally", "Often", "Almost always"],
  },
  {
    id: "q20",
    section: "Interview Quality & Decision Making",
    question: "What best describes your final hiring decisions?",
    type: "single",
    options: [
      "Mostly intuition / chemistry based",
      "Shared discussion with limited structure",
      "Evidence informed but still partly subjective",
      "Always structured and evidence-led",
    ],
  },
  {
    id: "q21",
    section: "Outcomes & Improvement Priorities",
    question: "Which hiring problems do you experience most often?",
    type: "multi",
    maxSelections: 3,
    options: [
      "Weak applicants",
      "Stakeholder misalignment",
      "Slow hiring process",
      "Poor hires despite strong interviews",
      "Inconsistent interviewer feedback",
      "First year attrition",
      "Difficulty comparing candidates",
    ],
  },
  {
    id: "q22",
    section: "Outcomes & Improvement Priorities",
    question: "How important is improving hiring accuracy over the next 12 months?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Not a focus", max: "Strategic priority" },
    scaleGuide: [
      { range: "1–3", label: "Not a major focus." },
      { range: "4–6", label: "Some improvement interest." },
      { range: "7–8", label: "Improving hiring quality is a priority." },
      { range: "9–10", label: "Improving hiring accuracy and reducing mis-hire risk is a strategic priority." },
    ],
  },
  {
    id: "q23",
    section: "Outcomes & Improvement Priorities",
    question: "If you could improve one part of your hiring process first, what would it be?",
    type: "single",
    options: [
      "Improve role definition and stakeholder alignment",
      "Better candidate attraction and employer branding",
      "Improving the quality of the talent pool",
      "Better candidate assessment and evaluation",
      "Improve interview quality and evidence validation",
      "Make better final hiring decisions and shortlist clarity",
    ],
  },
];

export const inhouseSectionNames = [
  "Role & Company Context",
  "Requirement Capture & Role Definition",
  "Job Adverts & Employer Branding",
  "Sourcing & Talent Pipeline",
  "Assessment & Evaluation",
  "Interview Quality & Decision Making",
  "Outcomes & Improvement Priorities",
];
